"2019-08-22 12:59:21,228 - status_tracer_decorator.py[line:73] - INFO: job status is failed"
"2019-08-22 12:59:21,288 - status_tracer_decorator.py[line:74] - INFO: Traceback (most recent call last):
  File "/fate/workflow/status_tracer_decorator.py", line 69, in wrapper
    res = func(self, *args, **kwargs)
  File "/fate/workflow/workflow.py", line 913, in run
    self.network_embedding(data_instances, node2id)
  File "/fate/workflow/workflow.py", line 215, in network_embedding
    self.nrler.fit(data_instances, node2id)
  File "/fate/federatedml/network_embedding/hetero_network_embedding/hetero_ne_guest.py", line 168, in fit
    fore_gradient = self.gradient_operator.compute_fore_gradient(batch_data_inst, en_aggregate_ee)
  File "/fate/federatedml/optim/gradient/logistic_gradient.py", line 342, in compute_fore_gradient
    fore_gradient = encrypted_ee.join(data_instance, lambda ee, d: 0.25 * ee - 0.5 * d.label)
  File "/fate/arch/api/standalone/eggroll.py", line 727, in join
    if other.count() > self.count():
  File "/fate/arch/api/standalone/eggroll.py", line 542, in count
    for p in range(self._partitions):
TypeError: 'NoneType' object cannot be interpreted as an integer
"
"2019-08-22 12:59:21,291 - status_tracer_decorator.py[line:59] - INFO: fail to post status failed"
